routes/routes.py
from flask import Blueprint, render_template, session, redirect, url_for, request, flash,jsonify, send_file, request
from service.gasto_service import GastoService
from io import BytesIO
import pandas as pd
from xhtml2pdf import pisa
import random
from datetime import datetime
from datetime import date
from collections import defaultdict
import calendar

from service.despesa_service import DespesaService

gasto_bp = Blueprint('gasto', __name__)
despesa_bp = Blueprint('despesa', __name__)


mensagens_erro = [
    "Senha ou usuario errado 🖕🏼 ",
    "Verifique suas credenciais ⚠️",
    "Seu usuario pode estar inativo 😕",
    "Cara, olha o que tu ta digitando 🤦🏽‍♂️",
    "Acesso negado! você é gay 🏳️‍🌈",
    "Tu é burro(a) ou tu é burro(a)? 🤦🏽‍♂️",
    "Vai bloquear teu usuario 😅",
    "Mds, quem sabe clica em redefinir senha 🤦🏽‍♂️",
]

#####ROTAS#####

def init_routes(app, gasto_service,despesa_service):
    print(app.url_map)
    app.register_blueprint(gasto_bp)
    app.register_blueprint(despesa_bp)

    # Armazena a instância do service dentro do blueprint
    gasto_bp.gasto_service = gasto_service
    despesa_bp.despesa_service = despesa_service

#def configure_routes(app, gasto_service):
@gasto_bp.route('/')
def login():
    return render_template('login.html')

@gasto_bp.route('/voltar_ao_login', methods=['GET','POST'])
def voltar_ao_login():
    return render_template('voltar_ao_login.html')

@gasto_bp.route('/login', methods=['POST'])
def login_post():
    if request.method == 'POST':
        usuario = request.form['email']
        print(usuario)
        senha = request.form['senha']
        print(senha)
        if gasto_bp.gasto_service.validar_login(usuario, senha):
            session['usuario'] = usuario
            
            dados = gasto_bp.gasto_service.filtrarGastos('mesatual',usuario)

            total_gasto = sum([
                float(item.get('valor', 0)) 
                for item in dados 
                if isinstance(item.get('valor', 0), (int, float)) or str(item.get('valor', 0)).replace('.', '', 1).isdigit()
            ])

            return redirect(url_for('gasto.index'))  # Redireciona para a tela principal
        else:
            erro = random.choice(mensagens_erro)
            flash(erro,"danger")
    return render_template('login.html')


@gasto_bp.route('/index')
def index():
    
    if 'usuario' not in session:
        
        return redirect(url_for('login'))

    usuario = session['usuario']  # Só acessa se já tiver passado pela verificação

    dados = gasto_bp.gasto_service.filtrarGastos('mesatual',usuario) #verifica_dados_bd(usuario)

    if not dados:
        dados = [('Alimentação', 0), ('Saúde', 0), ('Mobilidade', 0), ('Entretenimento', 0), ('Moradia', 0), ('Outros', 0), ('Dívidas', 0), ('Educação', 0)]

    total_gasto = sum([
    float(item['valor']) if isinstance(item, dict) and 'valor' in item else float(item[0])
    for item in dados
    if (
        (isinstance(item, dict) and isinstance(item.get('valor', 0), (int, float))) or 
        (isinstance(item, tuple) and len(item) > 0 and str(item[0]).replace('.', '', 1).isdigit())
    )
    ])

    return render_template('index.html')

@gasto_bp.route('/cadastrar_gasto', methods=['GET', 'POST'])
def cadastrar_gasto():
    if request.method == 'POST':
        print('cad entrou')
        if 'usuario' not in session:
            flash('Você precisa estar logado para adicionar um gasto.')
            return redirect('/login')

        gasto = request.form['gasto']
        valor = request.form['valor']
        data = request.form['data']
        categoria = request.form['categoria']
        
        usuario = session['usuario']
        
        # Salvar o gasto no banco
        sucesso = gasto_bp.gasto_service.salvar_gasto(gasto, valor, data, categoria,usuario)
        #flash('Gasto cadastrado com sucesso!', 'success')  

        return """<script>                    
                    window.location.href = '/extrato';
                </script>"""

    # return render_template('cadastrar_gasto.html')
    return extrato()  

@gasto_bp.route('/extrato', methods=['GET', 'POST'])
def extrato():
    usuario = session['usuario']

    page = request.args.get('page', 1, type=int)  # Obtém o número da página (padrão é 1)
    per_page = 12  # Número de gastos por página
    
     # pega data atual
    hoje = date.today()
    primeiro_dia = hoje.replace(day=1)

    # Pega filtros da URL ou define padrão
    data_inicio = request.args.get('data_inicio') or primeiro_dia.strftime('%Y-%m-%d')
    data_fim = request.args.get('data_fim') or hoje.strftime('%Y-%m-%d')
    categoria = request.args.get('categoria') or 'Todas'

    # Busca os gastos ordenados do mais recente para o mais antigo
    gastos = gasto_bp.gasto_service.extrato_gastos(usuario,data_inicio,data_fim,categoria)  

    total_gastos = len(gastos)

    start = (page - 1) * per_page
    end = start + per_page

    gastos_pagina = gastos[start:end]

    # Agrupar os gastos por data
    gastos_agrupados = defaultdict(list)
    for gasto in gastos_pagina:
        data = gasto[3]  # Supondo que o 4º item (índice 3) seja a data
        gastos_agrupados[data].append(gasto)


    # lista de categorias
    categorias = gasto_bp.gasto_service.get_categorias_disponiveis(usuario)

    gastos_pagina = gastos[start:end]

    soma_gastos = 0

    #se for geral do filtro selecionado
    soma_gastos = sum(gasto[2] for gasto in gastos)

    return render_template(
        'extrato.html',
        gastos_agrupados=gastos_agrupados,
        page=page,
        total=total_gastos,
        per_page=per_page,
        now=datetime.now(),
        data_inicio=data_inicio,
        data_fim=data_fim,
        categoria=categoria,
        soma_gastos=soma_gastos
    )


@gasto_bp.route('/filtrarGastos/<periodo>')
def filtrar(periodo):
    usuario = session['usuario']

    dados = gasto_bp.gasto_service.filtrarGastos(periodo,usuario)
    return jsonify(dados)


@gasto_bp.route("/cadastro", methods=["GET", "POST"])
def cadastro():
    if request.method == "POST":
        usuario = request.form["email"]
        senha = request.form["senha"]

        dados = gasto_bp.gasto_service.valida_usuario_existente(usuario,senha)   
        
        if dados:
            flash("Usuário já existe! 🤦🏽‍♂️")
            return redirect("/cadastro")

        flash("Usuário cadastrado com sucesso! 😄", "success")

        return render_template("cadastro.html")
    
    return render_template("cadastro.html")


@gasto_bp.route('/esqueci', methods=['GET', 'POST'])
def esqueci():
    return render_template("esqueci.html")    

@gasto_bp.route('/editar_gasto', methods=[ 'POST'])
def editar_gasto():

    if 'usuario' not in session:
        flash('Você precisa estar logado para adicionar um gasto.')
        return redirect('/login')

    gasto = request.form['gasto']
    valor = request.form['valor']
    data = request.form['data']
    categoria = request.form['categoria']
    
    id = request.form['id']

    # usuario = session['usuario']
    
    gasto_bp.gasto_service.editar_gasto(gasto,categoria,valor,data,id)

    return extrato() 

@gasto_bp.route('/deletar_gasto', methods=['POST'])
def deletar_gasto():
    print('foi')
    if 'usuario' not in session:
        flash('Você precisa estar logado para deletar um gasto.')
        return redirect('/login')

    id_gasto = request.form.get('id')

    print('gasto' + id_gasto)

    if not id_gasto:
        # flash('ID do gasto não fornecido!', 'danger')
        return redirect('/extrato')

    try:
        gasto_bp.gasto_service.deletar_gasto(id_gasto)
        # flash('Gasto deletado com sucesso!', 'success')
    except Exception as e:
        print("Erro ao deletar gasto:", e)
        flash('Erro ao tentar deletar o gasto. 😓', 'danger')

    return extrato() 

@despesa_bp.route('/despesas', methods=['GET'])
def despesas(): 
    usuario = session['usuario']
    
    # pega data atual
    hoje = date.today()
    primeiro_mes = hoje.replace(day=1)

    # Pega o filtro vindo da URL ou usa o primeiro dia do mês atual
    mes_ano_str = request.args.get('mes_ano') or primeiro_mes.strftime('%Y-%m')
    print(mes_ano_str)

    # Busca os gastos ordenados do mais recente para o mais antigo
    despesas = despesa_bp.despesa_service.busca_despesas(usuario,mes_ano_str,'Todas')  

    return render_template(
        'despesas.html',
        despesas=despesas,
        mes_ano=mes_ano_str[:7]  # yyyy-mm para o input month
    )

@despesa_bp.route('/despesas', methods=['POST'])
def atualizar_status():
    data = request.get_json()
    id_despesa = data.get('id_despesa')
    novo_status = data.get('novo_status')

    if not id_despesa or not novo_status:
        return jsonify({'erro': 'Dados incompletos'}), 400

    # Chama método da camada service para atualizar no banco
    sucesso = despesa_bp.despesa_service.atualizar_status(id_despesa, novo_status)

    if sucesso:
        return jsonify({'mensagem': 'Status atualizado com sucesso'})
    else:
        return jsonify({'erro': 'Falha ao atualizar'}), 500



@despesa_bp.route('/cadastrar_despesa', methods=['GET', 'POST'])
def cadastrar_despesa():
    print('foi')
    if request.method == 'POST':
        if 'usuario' not in session:
            flash('Você precisa estar logado para adicionar um gasto.')
            return redirect('/login')

        despesa = request.form['despesa']
        valor = request.form['valor']

        data = request.form['mes_ano']
        print(data)

        
        categoria = request.form['categoria']
        
        usuario = session['usuario']
        
        # Salvar o gasto no banco
        despesa_bp.despesa_service.salvar_despesa(despesa, valor, data, categoria,usuario)
        flash('Despesa cadastrada com sucesso!', 'success')  

        return """<script>                    
                    window.location.href = '/cadastrar_despesa';
                </script>"""

templates/cadastrar_despesa.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastrar Despesa</title>
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}"> -->
    <link rel="stylesheet" type="text/css" href="static/css/cad_despesas.css">
    
</head>
<body class="body-despesa">
    
    <div class="container-cadastro">

        {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div class="flash-message">
            {% for category, message in messages %}
                <div class="alert {{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>

        

    {% endif %}
{% endwith %}

        <h1>Cadastro de Despesa</h1>
        <form method="POST" action="{{ url_for('despesa.cadastrar_despesa') }}">
            <div class="form-group">
                <label for="despesa">Descrição</label>
                <input type="text" id="despesa" name="despesa" required placeholder="Descrição da Despesa">
            </div>
            <div class="form-group">
                <label for="valor">Valor</label>
                <input type="number" id="valor" name="valor" required placeholder="Valor da Despesa">
            </div>
            <div class="form-group">
                <!-- <label for="data">Data</label>
                <input type="date" id="data" name="data" required> -->

                <label for="data" style="font-weight: bold;">Selecione o mês:</label>
    <input type="month" id="data" name="mes_ano" style="padding: 5px; border-radius: 4px; border: 1px solid #ccc;" required>    

            </div>
            <div class="form-group">
                <label for="categoria">Categoria</label>
                <select id="categoria" name="categoria" required>
                    <option value="Alimentação">Alimentação</option>
                    <option value="Saúde">Saúde</option>
                    <option value="Mobilidade">Mobilidade</option>
                    <option value="Entretenimento">Entretenimento</option>
                    <option value="Moradia">Moradia</option>
                    <option value="Outros">Outros</option>
                    <option value="Dívidas">Dívidas</option>
                    <option value="Educação">Educação</option>
                </select>
            </div>
            
        <div class="button-container">
            <button type="submit" class="btn-save">Salvar</button>
            <a href="{{ url_for('despesa.despesas') }}" class="btn-voltar">Voltar</a>
        </div>
    </form>
    </div>
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>

</body>
</html>

templates/cadastro.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Usuário</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/cadastro_usu.css') }}">
</head>
<body>
    <div class="container">


      {% with messages = get_flashed_messages() %}
      {% if messages %}
        <div class="alert alert-success">
          {{ messages[0] }}
        </div>
      {% endif %}
    {% endwith %}

        <h3>Cadastro de Usuário</h3>
        <form class="form-box" action="{{ url_for('gasto.cadastro') }}" method="POST">
          <!-- <div class="validate-input" data-validate = "Um email válido deve conter: algumacoisa@algumaoutracoisa.c"> -->
          <input type="email" name="email" placeholder="Email" required >
            <input type="password" name="senha" placeholder="Senha" required>
        <!-- </div> -->
            <br><br>
            <button class="button-cad" type="submit">Cadastrar</button>

        <a href="/" class="btn-cad-usu">Voltar </a>
          </form>

    </div>
</body>
</html>

templates/esqueci.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <style>
        .img-responsiva {
            display: block;
            max-width: 100%;
            height: auto;
            margin: 0 auto;
        }

        .button-detalhes {
            display: inline-block;
            padding: 10px 20px;
            text-decoration: none;
            background: linear-gradient(135deg, #da4025f5, #bc3a1ae7);
            color: white;
            border-radius: 5px;


            border: none;
            cursor: pointer;
            transition: background-color 0.3s ease, transform 0.2s ease;
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
            font-weight: bold;
            font-size: 10px;
            display: inline-block;
            text-align: center;
        }

        .button{
            display: flex;
            justify-content: center;
        }
    </style>
</head>
<body>

    <img src="https://i.ytimg.com/vi/Mp0QGaVIbdE/maxresdefault.jpg" class="img-responsiva" alt="Imagem exemplo">
<br><br><br>
    <div class="button">
    <a href="{{ url_for('gasto.login') }}" class="button-detalhes">Voltar</a>
</div>
</body>
</html>

templates/extrato.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Extrato</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/extrato.css') }}">
    <script src="static/js/extrato.js" defer></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/litepicker/dist/css/litepicker.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.5.0/css/all.min.css">

<script src="https://cdn.jsdelivr.net/npm/litepicker/dist/litepicker.js"></script>
</head>
<body>
    <div class="container-detalhes" >

        <h2 style="text-align: center;">Extrato</h2>
            <!-- Filtro -->
<!-- Filtro -->
<form method="GET" action="{{ url_for('gasto.extrato') }}" class="filtro-form" id="filtro-form">
    <!-- Botão de período -->
    <div class="periodo-wrapper">
        <label for="data">Período:</label>
        <input type="text" id="periodo-picker" readonly placeholder="Selecione o período" />
        <input type="hidden" id="data_inicio" name="data_inicio" value="{{ data_inicio }}">
<input type="hidden" id="data_fim" name="data_fim" value="{{ data_fim }}">

<!-- <input type="hidden" id="categoria" name="categoria" value="{{ categoria }}"> -->
    </div>
    <!-- Dropdown de categoria -->
    <label for="categoria">Categoria:</label>
    <select name="categoria" id="categoria">
        <option value="Todas">Todas</option>
        <option value="Alimentação">Alimentação</option>
        <option value="Saúde">Saúde</option>
        <option value="Mobilidade">Mobilidade</option>
        <option value="Entretenimento">Entretenimento</option>
        <option value="Moradia">Moradia</option>
        <option value="Outros">Outros</option>
        <option value="Dívidas">Dívidas</option>
        <option value="Educação">Educação</option>

        {% for cat in categorias %}
            <option value="{{ cat }}" {% if request.args.get('categoria') == cat %}selected{% endif %}>{{ cat }}</option>
        {% endfor %}
    </select>

    <button type="submit" class="botao-filtrar">Filtrar</button>
</form>
<br>

        <table>
            <thead>
                <tr>
                    <!-- <th>Data</th> -->
                    <th>Categoria</th>
                    <th>Descrição</th>
                    <th>Valor (R$)</th>
                    <th colspan="2"> </th>

                    <!-- <th></th> -->
                </tr>
            </thead>
            <tbody>
             

                {% for data, lista in gastos_agrupados.items() %}
                <!-- Linha com a data -->
                <tr style="background-color: #f5f5f5;">
                    <td colspan="5" style="text-align: justify; padding: 8px 0;"><strong>📅 {{ data }}</strong></td>
                </tr>
            
                {% for gasto in lista %}
                    <tr class="gasto"
                    data-id="{{ gasto[4] }}"
                     style="background-color: {% if loop.index0 % 2 == 0 %}#eaffea{% else %}white{% endif %}; line-height: 1.6;">
                        <td>{{ gasto[0] }}</td>
                        <td>{{ gasto[1] }}</td>
                        <td>R$ {{ gasto[2] | round(2) }}</td>
                        <td>
                            <i class="fas fa-edit edit-icon"
                            data-data="{{ gasto[3] }}"
                            data-categoria="{{ gasto[0] }}"
                            data-descricao="{{ gasto[1] }}"
                            data-valor="{{ gasto[2] }}"
                            data-id="{{ gasto[4] }}"
                            title="Editar"></i>
                        </td>
                        <td>
                            <i class="fa-solid fa-trash"
                            data-id="{{ gasto[4] }}"
                            ></i>
                        </td>
                    </tr>
                {% endfor %}
            {% endfor %}
            

              </tbody>
              <tfoot>
                <tr>
                    <td colspan="2" style="text-align: left; font-weight: bold;">Total do período:</td>
                    <td></td>
                    <td colspan="2" style="font-weight: bold;">
                        R$ {{ '%.2f' | format(soma_gastos) }}
                    </td>
                </tr>
                
            </tfoot>
            
                      

        </table>

        <div style="text-align: right; margin-top: 10px;">
            <a href="{{ url_for('gasto.exportar_excel', data_inicio=request.args.get('data_inicio'), data_fim=request.args.get('data_fim'), categoria=request.args.get('categoria')) }}" class="button-detalhes" style="background: linear-gradient(135deg, #28a745, #218838);">Exportar Excel</a>

            <a href="{{ url_for('gasto.exportar_pdf', data_inicio=request.args.get('data_inicio'), data_fim=request.args.get('data_fim'), categoria=request.args.get('categoria')) }}" class="button-detalhes" style="background: linear-gradient(135deg, #e04b4bc9, #e62121);">Exportar PDF</a>
        </div>


        <!-- Paginação -->
        <div class="pagination">

                <!-- <a href="{{ url_for('gasto.cadastrar_gasto') }}"><button class="btn-left">Adicionar Gasto</button></a>  -->
                <button class="btn-left">Adicionar Gasto</button> 
            {% if page > 1 %}
                <!-- <a href="{{ url_for('gasto.extrato', page=page-1) }}" class="button">← Anterior</a> -->
                <a href="{{ url_for('gasto.extrato', page=page-1, data_inicio=request.args.get('data_inicio'), data_fim=request.args.get('data_fim'), categoria=request.args.get('categoria')) }}" class="button">← Anterior</a>

            {% endif %}
            
            <span>Página {{ page }}</span>

            {% if total > page * per_page %}
                <!-- <a href="{{ url_for('gasto.extrato', page=page+1) }}" class="button">Próxima →</a> -->
                <a href="{{ url_for('gasto.extrato', page=page+1, data_inicio=request.args.get('data_inicio'), data_fim=request.args.get('data_fim'), categoria=request.args.get('categoria')) }}" class="button">Próxima →</a>

            {% endif %}
            <a href="{{ url_for('gasto.index') }}" class="button-detalhes">Voltar</a>
        </div>

        
    </div>

<!-- Modal de Edição -->
<div id="modal-editar" class="modal" style="display: none;">
    <div class="modal-content">
      <span class="close" id="fechar-modal">&times;</span>
      <h3>Editar Gasto</h3>
      <form id="form-editar" method="POST" action="{{ url_for('gasto.editar_gasto') }}">
        <label for="editar-data">Data:</label>
        <input type="date" name="data" id="editar-data">
  
        <label for="editar-categoria">Categoria:</label>
        <!-- <input type="text" name="categoria" id="editar-categoria" required> -->
        <select name="categoria" id="editar-categoria">

            <option value="Alimentação">Alimentação</option>
            <option value="Saúde">Saúde</option>
            <option value="Mobilidade">Mobilidade</option>
            <option value="Entretenimento">Entretenimento</option>
            <option value="Moradia">Moradia</option>
            <option value="Outros">Outros</option>
            <option value="Dívidas">Dívidas</option>
            <option value="Educação">Educação</option>
        </select>
        <label for="editar-descricao">Descrição:</label>
        <input type="text" name="gasto" id="editar-descricao" required>
  
        <label for="editar-valor">Valor (R$):</label>
        <input type="number" step="0.01" name="valor" id="editar-valor" required>
  
        <input type="hidden" id="editar-id" name="id">

        <button type="submit" class="botao-salvar">Salvar</button>
      </form>
    </div>
  </div>
  
 <!-- Modal confirmação  -->
 <div id="modal-confirmar-exclusao" class="modal" style="display: none;">
    <div class="modal-content">
      <span class="close" id="fechar-modal-excluir">&times;</span>
      <h3>Tem certeza que deseja excluir este gasto?</h3>
      <form method="POST" action="{{ url_for('gasto.deletar_gasto') }}"> 
        <input type="hidden" id="id-gasto-excluir" name="id">
        <button type="submit" id="confirmar-exclusao" class="btn-ok" style="margin-top: 12px;">OK</button>
    </form>
    
    </div>
  </div>
  

<!-- Modal de Cadastro -->
<div id="modal-cadastrar" class="modal" style="display: none;">
    <div class="modal-content">
      <span class="close" id="fechar-modal-cadastro">&times;</span>
      <h3>cadastrar Gasto</h3>
      <form id="form-cadastrar" method="POST" action="{{ url_for('gasto.cadastrar_gasto') }}">
        <label for="cadastrar-data">Data:</label>
        <input type="date" name="data" id="cadastrar-data">
  
        <label for="cadastrar-categoria">Categoria:</label>
        <!-- <input type="text" name="categoria" id="cadastrar-categoria" required> -->
        <select name="categoria" id="cadastrar-categoria">

            <option value="Alimentação">Alimentação</option>
            <option value="Saúde">Saúde</option>
            <option value="Mobilidade">Mobilidade</option>
            <option value="Entretenimento">Entretenimento</option>
            <option value="Moradia">Moradia</option>
            <option value="Outros">Outros</option>
            <option value="Dívidas">Dívidas</option>
            <option value="Educação">Educação</option>
        </select>
        <label for="cadastrar-descricao">Descrição:</label>
        <input type="text" name="gasto" id="cadastrar-descricao" required>
  
        <label for="cadastrar-valor">Valor (R$):</label>
        <input type="number" step="0.01" name="valor" id="cadastrar-valor" required>
  
        <input type="hidden" id="cadastrar-id" name="id">

        <button type="submit" class="botao-salvar">Salvar</button>
      </form>
    </div>
  </div>


 <!-- Modal ok  -->
 <div id="modal-cadastro-ok" class="modal" style="display: none;">
    <div class="modal-content">
      <span class="close" id="fechar-modal-ok">&times;</span>
      <h4>Gasto Cadastrado com sucesso!</h4>
      <form method="POST"> 
        <input type="hidden" id="id-gasto" name="id">
        <button type="submit" id="confirmar-ok" class="botao-salvar" style="margin-top: 12px;">OK</button>
    </form>
    
    </div>
  </div>

<!-- Modal mensalista  -->
<div id="modal-mensalista" class="modal" style="display: none;">
    <div class="modal-content" style="background-color: #e96960;">
      <span class="mensalista" id="fechar-modal-mensalista">&times;</span>
      <h4 style="text-align: center; color: #f5f5f5;">Assinatura de mensalista vencida!</h4>
      <h4 style="text-align: center; color: #f5f5f5;">Contate o administrador.</h4>  
      <button type="submit" id="confirmar-ok" class="btn-ok" style="margin-top: 12px;">OK</button>  
    </div>
  </div>



</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dash de Finanças de Abner</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
 
<!-- <div class="container">
  <script>
    setTimeout(function() {
        document.getElementById('flash-message').style.display = 'none';
        window.location.href = '/';
    }, 3000); // Aguarda 3 segundos antes de redirecionar
</script> -->
  

<!-- <div class="period-container-wrapper">
  <button class="period-button" onclick="filtrarGastos('semanaatual')">Semana Atual</button>
  <button class="period-button" onclick="filtrarGastos('ontem')">Ontem</button>
  <button class="period-button" onclick="filtrarGastos('hoje')">Hoje</button>
  <button class="period-button" onclick="filtrarGastos('semanapassada')">Semana Passada</button>
  <button class="period-button" onclick="filtrarGastos('mesatual')">Mês Atual</button>
  <button class="period-button" onclick="filtrarGastos('mesanterior')">Mês Anterior</button>
</div> -->
<div class="container-btn">
<div class="period-container-wrapper" id="period-buttons">
  <button class="period-button " onclick="filtrarGastos('semanaatual')">Semana Atual</button>
  <button class="period-button " onclick="filtrarGastos('ontem')">Ontem</button>
  <button class="period-button " onclick="filtrarGastos('hoje')">Hoje</button>
  <button class="period-button " onclick="filtrarGastos('semanapassada')">Semana Passada</button>
  <button class="period-button " onclick="filtrarGastos('mesatual')">Mês Atual</button>
  <button class="period-button " onclick="filtrarGastos('mesanterior')">Mês Anterior</button>
</div>
</div>

<br><br>
 
  <div id="mensagem" style="display: none; color: red; font-weight: bold; text-align: center; margin-top: 10px;"></div>
  <div class="chart-container">
    <canvas id="donutChart"></canvas>
</div>

<div id="total" style="text-align: center; margin-top: 20px; ">
   <h3 class="txt1">Total Gasto no período: R$ <span id="valor-total">0,00</span></h3>
</div>
<br>
<div class="button-container">
  <!-- <a href="{{ url_for('gasto.cadastrar_gasto') }}"><button class="btn-left">Adicionar Gasto</button></a> -->
  <a href="{{ url_for('despesa.despesas') }}"><button class="btn-despesas">Visualizar Despesas</button></a>
  <!-- <button class="btn-right">extrato</button> -->
  <a href="{{ url_for('gasto.extrato') }}"><button class="btn-right">Detalhar Gastos</button></a>

  <a href="{{ url_for('gasto.login') }}" ><button class="btn-voltar">Sair</button></a>
</div>



  <script src="static/js/scripts.js" defer></script>
</body>
</html>